### ISSUE TITLE
问问题，编译过程的问题

### ISSUE THREAD

**Issue by QWQorz** [Jeff-Hugh/GenPorMed#11]
作者你好，我在编译过程中出现了
CMake Error at D:/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: regex iostreams system) (found suitable
  version "1.72.0", minimum required is "1.60")
请问我应该从哪里排查，我已经正常安装并配置了boost库，但是报错信息还是这样

**Comment by Jeff-Hugh** [comment]
在CMakelists.txt中关于boost库的设置为：

```
set(Boost_INCLUDE_DIR /usr/share/boost_1_72_0)
set(Boost_LIBRARY_DIR /usr/share/boost_1_72_0/lib)
FIND_PACKAGE( Boost 1.60 COMPONENTS regex iostreams system REQUIRED )
```

上述/usr/share/boost_1_72_0请替换成你的系统下的路径
第三行需要regex iostreams system三个包，请确保boost库安装完整且包含这三个包。

**Comment by QWQorz** [comment]
你好，解决了，谢谢作者，这个代码好像在windows平台上编译会有问题，换Linux就没有问题了

**Comment by Jeff-Hugh** [comment]
> 你好，解决了，谢谢作者，这个代码好像在windows平台上编译会有问题，换Linux就没有问题了

源代码确实是在Linux下完成的。
