### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by junyangli-SJTU** [Jeff-Hugh/GenPorMed#2]

**Comment by Jeff-Hugh** [comment]
需要先把boost库链接到项目中

**Comment by junyangli-SJTU** [comment]
> 需要先把boost库链接到项目中

已经链接到项目了
![image](https://user-images.githubusercontent.com/73172506/97826355-5c408280-1cfc-11eb-8db9-7d5480983427.png)
并且测试过简单代码，比如这个，编译运行都没问题
![image](https://user-images.githubusercontent.com/73172506/97826504-b04b6700-1cfc-11eb-969e-d667a7c2da68.png)
但是上面那个还报错报相同的错误，求问下是怎么回事，应该怎么解决？ 谢谢！
![image](https://user-images.githubusercontent.com/73172506/97827566-a4ad6f80-1cff-11eb-903b-8901af151ebc.png)

**Comment by Jeff-Hugh** [comment]
我已经重新测试过，最新提交的代码没有出现以上的错误。以下是我的工程目录
![Capture](https://user-images.githubusercontent.com/7226171/97832163-1344fa00-1d0d-11eb-8b70-5ba67309ef94.PNG)
请确定两个设置已经完成
（1）项目属性附加目录包括boost，链接器附加库目录包括boost/stage/lib
（2）由于程序中出现递归操作，请适当增加堆栈大小（链接器-系统-堆栈保留大小）

如在Linux环境下，直接make就好。

**Comment by junyangli-SJTU** [comment]
感谢！不好意思，我尝试还是出现相应的错误。请问您用的也是vs2012吗？可否直接邮件发个压缩整个打包的解决方案工程文件（包括boost的packages），也就是您刚测试过的，我看看具体问题在哪里。再次感谢！

junyangli@sjtu.edu.cn

**Comment by Jeff-Hugh** [comment]
> 感谢！不好意思，我尝试还是出现相应的错误。请问您用的也是vs2012吗？可否直接邮件发个压缩整个打包的解决方案工程文件（包括boost的packages），也就是您刚测试过的，我看看具体问题在哪里。再次感谢！
> 
> [junyangli@sjtu.edu.cn](mailto:junyangli@sjtu.edu.cn)

我用的是VS 2019社区版，boost库编译后特别大，不太好打包。我抽时间录一下整个过程给你看吧。

**Comment by junyangli-SJTU** [comment]
> > 感谢！不好意思，我尝试还是出现相应的错误。请问您用的也是vs2012吗？可否直接邮件发个压缩整个打包的解决方案工程文件（包括boost的packages），也就是您刚测试过的，我看看具体问题在哪里。再次感谢！
> > [junyangli@sjtu.edu.cn](mailto:junyangli@sjtu.edu.cn)
> 
> 我用的是VS 2019社区版，boost库编译后特别大，不太好打包。我抽时间录一下整个过程给你看吧。

好的，太感谢了！您装boost是什么版本，通过从官网下载手动安装的吗？像这个里面前半部分吗？ https://www.jianshu.com/p/4a093f8cde3c     我是通过他讲的后半部分 用VS2012里面Nuget弄的

**Comment by Jeff-Hugh** [comment]
> > > 感谢！不好意思，我尝试还是出现相应的错误。请问您用的也是vs2012吗？可否直接邮件发个压缩整个打包的解决方案工程文件（包括boost的packages），也就是您刚测试过的，我看看具体问题在哪里。再次感谢！
> > > [junyangli@sjtu.edu.cn](mailto:junyangli@sjtu.edu.cn)
> > 
> > 
> > 我用的是VS 2019社区版，boost库编译后特别大，不太好打包。我抽时间录一下整个过程给你看吧。
> 
> 好的，太感谢了！您装boost是什么版本，通过从官网下载手动安装的吗？像这个里面前半部分吗？ https://www.jianshu.com/p/4a093f8cde3c 我是通过他讲的后半部分 用VS2012里面Nuget弄的

我是自己编译的

**Comment by junyangli-SJTU** [comment]
不好意思再打扰您啊，这两天又重新编译尝试了，还是那样
![image](https://user-images.githubusercontent.com/73172506/98757410-73bbf180-2407-11eb-8efa-37bb32f0c492.png)
我是反复按照网上的说明https://www.jianshu.com/p/4a093f8cde3c 
设置项目属性附加目录包括boost，链接器附加库目录包括boost/stage/lib，但不知道为什么还是报错，像简单代码这样，这个代码里面库都能加载，没问题
![image](https://user-images.githubusercontent.com/73172506/98755758-2d18c800-2404-11eb-9cae-b412d1cf06f1.png)

但是我发现这个库就加载不了，#include <boost/iostreams/device/file_descriptor.hpp>，报错会提示：LINK : fatal error LNK1104: 无法打开文件“libboost_iostreams-vc110-mt-sgd-x32-1_72.lib”。

还麻烦问下除了链接boost库是不是还得单独下载Gnuplot？这也是个库还是单独的应用程序？

**Comment by Jeff-Hugh** [comment]
> 不好意思再打扰您啊，这两天又重新编译尝试了，还是那样
> ![image](https://user-images.githubusercontent.com/73172506/98757410-73bbf180-2407-11eb-8efa-37bb32f0c492.png)
> 我是反复按照网上的说明https://www.jianshu.com/p/4a093f8cde3c
> 设置项目属性附加目录包括boost，链接器附加库目录包括boost/stage/lib，但不知道为什么还是报错，像简单代码这样，这个代码里面库都能加载，没问题
> ![image](https://user-images.githubusercontent.com/73172506/98755758-2d18c800-2404-11eb-9cae-b412d1cf06f1.png)
> 
> 但是我发现这个库就加载不了，#include <boost/iostreams/device/file_descriptor.hpp>，报错会提示：LINK : fatal error LNK1104: 无法打开文件“libboost_iostreams-vc110-mt-sgd-x32-1_72.lib”。
> 
> 还麻烦问下除了链接boost库是不是还得单独下载Gnuplot？这也是个库还是单独的应用程序？

（1）boost安装教程的建议参考官方网站
（2）gnuplot只是为了输出png图片，boost库是为了支持gnuplot出图。你完全可以注释掉output2png()这个程序，这样就不依赖boost库，只输出tecplot的画图文件。
（3）最近有点忙，没时间做视频给你，抱歉。
