### ISSUE TITLE
1

### ISSUE THREAD

**Issue by junyangli-SJTU** [Jeff-Hugh/GenPorMed#3]

**Comment by Jeff-Hugh** [comment]
> ![image](https://user-images.githubusercontent.com/73172506/98913142-f032fb00-2501-11eb-95ce-1f11c0d0acfd.png)
> 请问这个地方第26行末尾的{}是必须的吗？我运行编译这个地方会报错，去掉后才好了。
> 还有请问运行后为什么始终porosity为1从而死循环？
> ![image](https://user-images.githubusercontent.com/73172506/98913310-28d2d480-2502-11eb-987d-992a90e9afc5.png)
> 之后我在这个地方加了输出（第38行）后发现
> ![image](https://user-images.githubusercontent.com/73172506/98935852-1c10a980-251f-11eb-8cd7-c5302e4d5dc2.png)
> 输出solid[cell]一直为这个
> ![image](https://user-images.githubusercontent.com/73172506/98935922-334f9700-251f-11eb-84b1-b80f90e0375a.png)

（1）下面这句是C++11标准的初始化列表功能，全部初始化为0
this->Solid = new int[NX*NY*NZ]{};
（2）可能由于没有初始化成功，才会出现porosity为1的情况。

修正：编译时采用C++11标准

**Comment by junyangli-SJTU** [comment]
> > ![image](https://user-images.githubusercontent.com/73172506/98913142-f032fb00-2501-11eb-95ce-1f11c0d0acfd.png)
> > 请问这个地方第26行末尾的{}是必须的吗？我运行编译这个地方会报错，去掉后才好了。
> > 还有请问运行后为什么始终porosity为1从而死循环？
> > ![image](https://user-images.githubusercontent.com/73172506/98913310-28d2d480-2502-11eb-987d-992a90e9afc5.png)
> > 之后我在这个地方加了输出（第38行）后发现
> > ![image](https://user-images.githubusercontent.com/73172506/98935852-1c10a980-251f-11eb-8cd7-c5302e4d5dc2.png)
> > 输出solid[cell]一直为这个
> > ![image](https://user-images.githubusercontent.com/73172506/98935922-334f9700-251f-11eb-84b1-b80f90e0375a.png)
> 
> （1）下面这句是C++11标准的初始化列表功能，全部初始化为0
> this->Solid = new int[NX_NY_NZ]{};
> （2）可能由于没有初始化成功，才会出现porosity为1的情况。
> 
> 修正：编译时采用C++11标准

可以只对这句代码更改，产生相同作用（也就是全部初始化为0）吗？
我现在用VS2012弄C++11标准编译似乎比较麻烦，可以只改这句代码吗？如果要改应该怎么改？不好意思，我对列表不是太熟悉，麻烦您了。

**Comment by Jeff-Hugh** [comment]
@junyangli-SJTU 你自己写个循环初始化为0就可以。

**Comment by junyangli-SJTU** [comment]
> @junyangli-SJTU 你自己写个循环初始化为0就可以。
this->Solid = new int[NXNYNZ]{};这个改成下面这样是不是就可以了？
![image](https://user-images.githubusercontent.com/73172506/99324674-bf5f1700-28af-11eb-94e9-7ab64acaa238.png)
