### ISSUE TITLE
the problem is  unlink iostream library?

### ISSUE THREAD

**Issue by scout7777758** [Jeff-Hugh/GenPorMed#4]
Dear Dr Jeff
when I 'make' on the terminal,I get some error , the error are as follows:

g++ -std=c++11 -fopenmp -c Porous2D.cpp -o Porous2D.o
g++ -std=c++11 -fopenmp -c run.cpp -o run.o
g++ -std=c++11 -fopenmp -c Porous3D.cpp -o Porous3D.o
g++ -fopenmp -lboost_system -lboost_iostreams -o run ./Porous2D.o ./run.o ./Porous3D.o
/usr/bin/ld: ./Porous2D.o: in function `boost::iostreams::stream<boost::iostreams::file_descriptor_sink, std::char_traits<char>, std::allocator<char> >::stream<int, boost::iostreams::file_descriptor_flags>(int const&, boost::iostreams::file_descriptor_flags const&, boost::disable_if<boost::is_same<int, boost::iostreams::file_descriptor_sink>, void>::type*)':
Porous2D.cpp:(.text._ZN5boost9iostreams6streamINS0_20file_descriptor_sinkESt11char_traitsIcESaIcEEC2IiNS0_21file_descriptor_flagsEEERKT_RKT0_PNS_10disable_ifINS_7is_sameIS9_S2_EEvE4typeE[_ZN5boost9iostreams6streamINS0_20file_descriptor_sinkESt11char_traitsIcESaIcEEC2IiNS0_21file_descriptor_flagsEEERKT_RKT0_PNS_10disable_ifINS_7is_sameIS9_S2_EEvE4typeE]+0x8e): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(int, boost::iostreams::file_descriptor_flags)'
/usr/bin/ld: ./Porous2D.o: in function `boost::iostreams::file_descriptor_sink boost::iostreams::detail::wrap<boost::iostreams::file_descriptor_sink>(boost::iostreams::file_descriptor_sink const&, boost::disable_if<boost::iostreams::is_std_io<boost::iostreams::file_descriptor_sink>, void>::type*)':
Porous2D.cpp:(.text._ZN5boost9iostreams6detail4wrapINS0_20file_descriptor_sinkEEET_RKS4_PNS_10disable_ifINS0_9is_std_ioIS4_EEvE4typeE[_ZN5boost9iostreams6detail4wrapINS0_20file_descriptor_sinkEEET_RKS4_PNS_10disable_ifINS0_9is_std_ioIS4_EEvE4typeE]+0x27): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
/usr/bin/ld: ./Porous2D.o: in function `boost::iostreams::detail::concept_adapter<boost::iostreams::file_descriptor_sink>::concept_adapter(boost::iostreams::file_descriptor_sink const&)':
Porous2D.cpp:(.text._ZN5boost9iostreams6detail15concept_adapterINS0_20file_descriptor_sinkEEC2ERKS3_[_ZN5boost9iostreams6detail15concept_adapterINS0_20file_descriptor_sinkEEC5ERKS3_]+0x23): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
/usr/bin/ld: ./Porous2D.o: in function `boost::iostreams::detail::concept_adapter<boost::iostreams::file_descriptor_sink>::concept_adapter(boost::iostreams::detail::concept_adapter<boost::iostreams::file_descriptor_sink> const&)':
Porous2D.cpp:(.text._ZN5boost9iostreams6detail15concept_adapterINS0_20file_descriptor_sinkEEC2ERKS4_[_ZN5boost9iostreams6detail15concept_adapterINS0_20file_descriptor_sinkEEC5ERKS4_]+0x23): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
/usr/bin/ld: ./Porous2D.o: in function `long boost::iostreams::detail::write_device_impl<boost::iostreams::output>::write<boost::iostreams::file_descriptor_sink>(boost::iostreams::file_descriptor_sink&, boost::iostreams::char_type_of<boost::iostreams::file_descriptor_sink>::type const*, long)':
Porous2D.cpp:(.text._ZN5boost9iostreams6detail17write_device_implINS0_6outputEE5writeINS0_20file_descriptor_sinkEEElRT_PKNS0_12char_type_ofIS7_E4typeEl[_ZN5boost9iostreams6detail17write_device_implINS0_6outputEE5writeINS0_20file_descriptor_sinkEEElRT_PKNS0_12char_type_ofIS7_E4typeEl]+0x2b): undefined reference to `boost::iostreams::file_descriptor::write(char const*, long)'
/usr/bin/ld: ./Porous2D.o: in function `std::fpos<__mbstate_t> boost::iostreams::detail::seek_device_impl<boost::iostreams::any_tag>::seek<boost::iostreams::file_descriptor_sink>(boost::iostreams::file_descriptor_sink&, long, std::_Ios_Seekdir, std::_Ios_Openmode)':
Porous2D.cpp:(.text._ZN5boost9iostreams6detail16seek_device_implINS0_7any_tagEE4seekINS0_20file_descriptor_sinkEEESt4fposI11__mbstate_tERT_lSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN5boost9iostreams6detail16seek_device_implINS0_7any_tagEE4seekINS0_20file_descriptor_sinkEEESt4fposI11__mbstate_tERT_lSt12_Ios_SeekdirSt13_Ios_Openmode]+0x3b): undefined reference to `boost::iostreams::file_descriptor::seek(long, std::_Ios_Seekdir)'
/usr/bin/ld: ./Porous2D.o: in function `void boost::iostreams::detail::close_impl<boost::iostreams::closable_tag>::close<boost::iostreams::file_descriptor_sink>(boost::iostreams::file_descriptor_sink&, std::_Ios_Openmode)':
Porous2D.cpp:(.text._ZN5boost9iostreams6detail10close_implINS0_12closable_tagEE5closeINS0_20file_descriptor_sinkEEEvRT_St13_Ios_Openmode[_ZN5boost9iostreams6detail10close_implINS0_12closable_tagEE5closeINS0_20file_descriptor_sinkEEEvRT_St13_Ios_Openmode]+0x25): undefined reference to `boost::iostreams::file_descriptor::close()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:9：run] error 1

Could you tell me how can I solve this problem?
Thankyou very much!

**Comment by Jeff-Hugh** [comment]
@scout7777758 I am sorry for the wrong Makefile. I update the compile method for this project. Please review the README.md file.
