### ISSUE TITLE
There is no output2png method in the Porous3D class

### ISSUE THREAD

**Issue by VictorCardoso** [Jeff-Hugh/GenPorMed#5]
Dear @Jeff-Hugh ,

It seems that there is no **output2png** method in the **Porous3D** class. Could you check this information, please?

Thank you in advance.

**Comment by Jeff-Hugh** [comment]
> 

Because one image can not show all layers of a 3D porous medium, I did not write the method. If you need one layer image, you can use the Slice function in Tecplot.

**Comment by VictorCardoso** [comment]
Thank you, Jeff.
