### ISSUE TITLE
How long it will take after the example program runs once

### ISSUE THREAD

**Issue by AlphaChau** [Jeff-Hugh/GenPorMed#6]

**Comment by Jeff-Hugh** [comment]
@AlphaChau 

My syetem info:
CPU: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz   2.90 GHz
RAM: 8G
System: Windows 10 21H2, 64-bit OS

2D example, size = 200*200, porosity = 0.5, Total Time = 0.805 s
3D example, size = 50*50*50, porosity = 0.5, Total Time = 3.027 s

**Comment by AlphaChau** [comment]
> @AlphaChau
> 
> My syetem info: CPU: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz 2.90 GHz RAM: 8G System: Windows 10 21H2, 64-bit OS
> 
> 2D example, size = 200_200, porosity = 0.5, Total Time = 0.805 s 3D example, size = 50_50*50, porosity = 0.5, Total Time = 3.027 s

Thanks, I just tested this program last night, got the same result. By the way, have you made some trials to add some more phases onto this model, to simulate a more complicated porous structure (like sand-water-gas three-phase structure), or to transplant the code to Matlab?

Thanks again for your reply.

**Comment by Jeff-Hugh** [comment]
> 

I use this porous structure to do some research on two-phase flow and machine learning. There are no plans to transplant this to other languages.
