### ISSUE TITLE
Failed to continue executing the code because BOOST_IOstreams - VC142-MT-GD-X64-1_77.dll could not be found. Reinstalling the program may resolve this problem.

### ISSUE THREAD

**Issue by albert-jeffery** [Jeff-Hugh/GenPorMed#7]
hello, please help me, After I compile at window and I used the visual studio 2019 to run the code, the following error is happen:
Failed to continue executing the code because BOOST_IOstreams - VC142-MT-GD-X64-1_77.dll could not be found. Reinstalling the program may resolve this problem.

**Comment by albert-jeffery** [comment]
These problems are solved when I use Linux, but I don't know how to use Gnuplot with your code

**Comment by Jeff-Hugh** [comment]
> These problems are solved when I use Linux, but I don't know how to use Gnuplot with your code

(1) Install gnuplot in your OS with yum or apt command. Then make sure you can run the gnuplot command in the program environment. 
(2) When compiling, the [gnuplot-iostream.h](https://github.com/Jeff-Hugh/GenPorMed/blob/master/gnuplot-iostream.h) will be included.
(3) When you run the executable file, the gnuplot can generate a 2D porous medium image.
