### ISSUE TITLE
问问题

### ISSUE THREAD

**Issue by albert-jeffery** [Jeff-Hugh/GenPorMed#8]
你好，请教一下，起初我用这份代码中的2D文件去生成图片，如何发现每一张图片都是，一样的，然后我就发现是随机种子的问题，于是问我就在run.cpp的文件中Generate2D函数中写了一个for循环，但是生成出来的图片堆叠起来生成的3D模型特别奇怪，我不知道是哪里的问题，麻烦回答一下，谢谢。我现在想要的是用这份代码去生成一系列图片，这些图片可以堆叠起来一个类似你在readme中的3D模型的效果。

**Comment by Jeff-Hugh** [comment]
不能把QSGS方法产出的二维图片简单堆叠组成三维多孔介质。请阅读参考文献理解一下本方法的思路。
